# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/server/smartbin/classify/new_data')),
            ],
        ),
    ]
